version: '3'
services:
  # users:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.users
  #   ports:
  #     - "8081:8081"
  #   env_file:
  #     - .env

  blogs:
    build:
      context: .
      dockerfile: Dockerfile.blogs
    ports:
      - "8082:8082"
    env_file:
      - .env

  # comments:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.comments
  #   ports:
  #     - "8083:8083"
  #   env_file:
  #     - .env

  # auth:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.auth
  #   ports:
  #     - "8084:8084"
  #   env_file:
  #     - .env
      