version: '3'
services:
  users:
    build:
      context: .
      dockerfile: Dockerfile.users
    ports:
      - "8081:8081"
    env_file:
      - .env

  blogs:
    build:
      context: .
      dockerfile: Dockerfile.blogs
    ports:
      - "8082:8082"
    env_file:
      - .env

  comments:
    build:
      context: .
      dockerfile: Dockerfile.comments
    ports:
      - "8083:8083"
    env_file:
      - .env

  graphql:
    build:
      context: .
      dockerfile: Dockerfile.graphql
    ports:
      - "4000:4000"
    env_file:
      - .env
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - .env  