version: '3'
services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8084:8084"
    depends_on:
      - db

  blog-service:
    build:
      context: ./blog-service
    ports:
      - "8082:8082"
    depends_on:
      - db

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - db

  comment-service:
    build:
      context: ./comment-service
    ports:
      - "8083:8083"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
