name: Publish Docker images to Docker Hub and GitHub Packages

on:
  push:
    branches: ['main']

jobs:
  push_to_registries:
    name: Push Docker images to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
    env:
        EDGE_STORE_ACCESS_KEY: ${{ secrets.EDGE_STORE_ACCESS_KEY }}
        EDGE_STORE_SECRET_KEY: ${{ secrets.EDGE_STORE_SECRET_KEY }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker images for each Dockerfile
      - name: Build and push Docker image for Dockerfile.auth
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile.auth
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/haalsamachar-auth:${{ github.sha }}

      - name: Build and push Docker image for Dockerfile.blogs
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile.blogs
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/haalsamachar-blogs:${{ github.sha }}

      - name: Build and push Docker image for Dockerfile.comments
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile.comments
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/haalsamachar-comments:${{ github.sha }}

      - name: Build and push Docker image for Dockerfile.graph
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile.graph
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/haalsamachar-graph:${{ github.sha }}

      - name: Build and push Docker image for Dockerfile.users
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile.users
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/haalsamachar-users:${{ github.sha }}

      - name: Build and push Docker image for Dockerfile.frontend
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        env:
            CI: false
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/haalsamachar-frontend:${{ github.sha }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
